# Generated by Django 5.2.13 on 2026-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_submit_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="bloom_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("remember", "Remember"),
                    ("understand", "Understand"),
                    ("apply", "Apply"),
                    ("analyze", "Analyze"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                blank=True,
                choices=[("mcq", "Multiple Choice"), ("true_false", "True/False")],
                default="mcq",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="generation_error",
            field=models.TextField(blank=True),
        ),
    ]
