# Generated by Codex on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0005_enrollment_completed_at_enrollment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="platform_name",
            field=models.CharField(default="LearnCode", max_length=120),
        ),
        migrations.AddField(
            model_name="certificate",
            name="platform_website",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="certificate",
            name="instructor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="certificate",
            name="course_duration",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="certificate",
            name="verification_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="certificate",
            name="ceo_name",
            field=models.CharField(default="Shemsa Amin", max_length=120),
        ),
        migrations.AddField(
            model_name="certificate",
            name="ceo_title",
            field=models.CharField(default="Chief Executive Officer", max_length=120),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
