# Generated by Django 5.2.13 on 2026-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_youtube_only_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ai_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='embedded_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_notes',
            field=models.FileField(blank=True, upload_to='pdf_notes/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript_text',
            field=models.TextField(blank=True),
        ),
    ]
