# Generated by Django 5.2.16 on 2026-07-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="playgroundchallenge",
            new_name="playground__user_id_252c61_idx",
            old_name="playground__user_id_7a8b2d_idx",
        ),
    ]
