# Generated by Django 5.2.13 on 2026-06-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('courses', '0003_lesson_source_refresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAIProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('transcript_text', models.TextField(blank=True)),
                ('analysis_json', models.JSONField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'lesson AI processing',
                'verbose_name_plural': 'lesson AI processing records',
                'ordering': ('-updated_at',),
            },
        ),
    ]
