"""Collect analytics data and render professional PDF reports."""

from __future__ import annotations

from datetime import date, datetime
from io import BytesIO
from typing import Any

from django.contrib.auth import get_user_model
from django.db.models import Avg, Count, Q
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from ai_engine.models import LessonAIProcessing, Recommendation, WeakTopic
from courses.models import Course, Lesson
from progress.models import Enrollment, LessonProgress
from progress.services.completion import quiz_passed_for_lesson
from quizzes.models import Question, Quiz, QuizResult

User = get_user_model()


class ReportDataError(Exception):
    """Raised when report data is missing or invalid."""

    def __init__(self, message: str, status_code: int = 400):
        super().__init__(message)
        self.message = message
        self.status_code = status_code


def _parse_date(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return datetime.strptime(value.strip()[:10], "%Y-%m-%d").date()
    except ValueError as exc:
        raise ReportDataError("Invalid date format. Use YYYY-MM-DD.", status_code=400) from exc


def _date_range_filter(from_date: date | None, to_date: date | None) -> Q:
    q = Q()
    if from_date:
        q &= Q(taken_at__date__gte=from_date)
    if to_date:
        q &= Q(taken_at__date__lte=to_date)
    return q


def _admin_course_ids(admin_user) -> list[int]:
    return list(Course.objects.filter(created_by=admin_user).values_list("id", flat=True))


def _admin_lesson_ids(course_ids: list[int]) -> list[int]:
    if not course_ids:
        return []
    return list(Lesson.objects.filter(course_id__in=course_ids).values_list("id", flat=True))


def _fmt(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.1f}"
    return str(value)


PLATFORM_NAME = "AI-Powered E-Learning Platform"
OFFICIAL_SUBTITLE = "Official Learning Analytics Report"
FOOTER_TEXT = "Generated by AI-Powered E-Learning Platform | Confidential Academic Report"


def _draw_pdf_footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.drawString(doc.leftMargin, 0.45 * inch, FOOTER_TEXT)
    canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.45 * inch, f"Page {canvas.getPageNumber()}")
    canvas.setStrokeColor(colors.HexColor("#cbd5e1"))
    canvas.line(doc.leftMargin, 0.62 * inch, doc.pagesize[0] - doc.rightMargin, 0.62 * inch)
    canvas.restoreState()


def _pdf_response(
    *,
    report_type: str,
    report_title: str,
    generated_by: str,
    sections: list[tuple[str, list[tuple[str, str]]]],
    tables: list[dict] | None = None,
) -> bytes:
    buffer = BytesIO()
    generated_at = timezone.now().strftime("%Y-%m-%d %H:%M UTC")
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.95 * inch,
        bottomMargin=0.85 * inch,
    )
    styles = getSampleStyleSheet()
    platform_style = ParagraphStyle(
        "PlatformName",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#0f766e"),
        spaceAfter=2,
        fontName="Helvetica-Bold",
    )
    official_style = ParagraphStyle(
        "OfficialTitle",
        parent=styles["Heading1"],
        fontSize=16,
        leading=20,
        spaceAfter=10,
        textColor=colors.HexColor("#0f172a"),
    )
    meta_style = ParagraphStyle(
        "MetaLine",
        parent=styles["Normal"],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#475569"),
        spaceAfter=2,
    )
    section_style = ParagraphStyle(
        "SectionTitle",
        parent=styles["Heading2"],
        fontSize=12,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor("#134e4a"),
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "BodyText",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"),
    )

    story = [
        Paragraph(PLATFORM_NAME, platform_style),
        Paragraph(OFFICIAL_SUBTITLE, official_style),
        Paragraph(f"<b>Report Type:</b> {report_type}", meta_style),
        Paragraph(f"<b>Report Title:</b> {report_title}", meta_style),
        Paragraph(f"<b>Generated On:</b> {generated_at}", meta_style),
        Paragraph(f"<b>Generated By:</b> {generated_by}", meta_style),
        Spacer(1, 0.15 * inch),
    ]

    table_header_style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ecfdf5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#065f46")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]

    for index, (section_title, rows) in enumerate(sections):
        story.append(Paragraph(section_title, section_style))
        if rows:
            table_data = [["Metric", "Value"]] + [[label, _fmt(val)] for label, val in rows]
            table = Table(table_data, colWidths=[3.4 * inch, 3.1 * inch])
            table.setStyle(TableStyle(table_header_style))
            story.append(table)
        elif index == 0:
            story.append(Paragraph("No summary metrics available.", body_style))
        story.append(Spacer(1, 0.08 * inch))

    for table_spec in tables or []:
        story.append(Paragraph(table_spec["title"], section_style))
        data = [table_spec["headers"]] + table_spec["rows"]
        if len(data) <= 1:
            story.append(Paragraph("No data available.", body_style))
        else:
            col_count = len(table_spec["headers"])
            width = 6.5 / col_count * inch
            table = Table(data, colWidths=[width] * col_count, repeatRows=1)
            table.setStyle(TableStyle(table_header_style))
            story.append(table)
        story.append(Spacer(1, 0.12 * inch))

    doc.build(story, onFirstPage=_draw_pdf_footer, onLaterPages=_draw_pdf_footer)
    return buffer.getvalue()


def build_admin_summary_report(admin_user, *, from_date: str | None = None, to_date: str | None = None) -> bytes:
    start = _parse_date(from_date)
    end = _parse_date(to_date)
    course_ids = _admin_course_ids(admin_user)
    lesson_ids = _admin_lesson_ids(course_ids)

    total_students = User.objects.filter(role=User.Role.STUDENT).count()
    total_courses = len(course_ids)
    total_lessons = len(lesson_ids)
    total_enrollments = Enrollment.objects.filter(course_id__in=course_ids).count() if course_ids else 0

    quiz_filter = _date_range_filter(start, end)
    quiz_results = QuizResult.objects.filter(quiz__lesson_id__in=lesson_ids).filter(quiz_filter) if lesson_ids else QuizResult.objects.none()
    total_quizzes_taken = quiz_results.count()
    avg_score = quiz_results.aggregate(value=Avg("score"))["value"]

    total_weak_topics = WeakTopic.objects.count()
    active_recommendations = Recommendation.objects.filter(status="active").count()

    quiz_qs = Quiz.objects.filter(lesson_id__in=lesson_ids) if lesson_ids else Quiz.objects.none()
    ai_success = quiz_qs.filter(generation_status=Quiz.GenerationStatus.DONE).count()
    ai_failed = quiz_qs.filter(generation_status=Quiz.GenerationStatus.FAILED).count()
    ai_pending = quiz_qs.exclude(
        generation_status__in=[Quiz.GenerationStatus.DONE, Quiz.GenerationStatus.FAILED]
    ).count()

    if total_courses == 0 and total_students == 0:
        raise ReportDataError("No platform data available for this admin account.", status_code=404)

    sections = [
        (
            "Executive Summary",
            [
                ("Total students", total_students),
                ("Total courses (owned)", total_courses),
                ("Total lessons", total_lessons),
                ("Total enrollments", total_enrollments),
                ("Quizzes taken", total_quizzes_taken),
                ("Average quiz score", round(float(avg_score), 1) if avg_score is not None else "—"),
                ("Total weak topics tracked", total_weak_topics),
                ("Active recommendations", active_recommendations),
            ],
        ),
        (
            "AI Quiz Generation Summary",
            [
                ("Successful generations", ai_success),
                ("Failed generations", ai_failed),
                ("Pending / processing", ai_pending),
            ],
        ),
    ]

    top_weak = list(
        WeakTopic.objects.values("topic_tag")
        .annotate(student_count=Count("user_id", distinct=True))
        .order_by("-student_count")[:10]
    )
    weak_rows = [[row["topic_tag"], str(row["student_count"])] for row in top_weak]

    rec_rows = list(
        Recommendation.objects.filter(status="active")
        .values("weak_topic_tag")
        .annotate(count=Count("id"))
        .order_by("-count")[:10]
    )
    recommendation_table = [
        [row["weak_topic_tag"] or "general", str(row["count"])] for row in rec_rows
    ]

    tables = [
        {
            "title": "Top Weak Topics",
            "headers": ["Topic", "Students Affected"],
            "rows": weak_rows,
        },
        {
            "title": "Recommendations Summary",
            "headers": ["Weak Topic Tag", "Active Count"],
            "rows": recommendation_table,
        },
    ]
    return _pdf_response(
        report_type="Admin Summary Report",
        report_title="Platform Summary",
        generated_by=admin_user.email,
        sections=sections,
        tables=tables,
    )


def build_admin_courses_report(admin_user, *, course_id: int | None = None, from_date: str | None = None, to_date: str | None = None) -> bytes:
    start = _parse_date(from_date)
    end = _parse_date(to_date)
    courses = Course.objects.filter(created_by=admin_user).annotate(lesson_count=Count("lessons", distinct=True))
    if course_id:
        courses = courses.filter(pk=course_id)
        if not courses.exists():
            raise ReportDataError("Invalid course id.", status_code=404)

    courses = list(courses.order_by("title"))
    if not courses:
        raise ReportDataError("No courses available for report.", status_code=404)

    rows = []
    for course in courses:
        lesson_ids = list(course.lessons.values_list("id", flat=True))
        enrolled = Enrollment.objects.filter(course_id=course.id).count()
        quiz_filter = _date_range_filter(start, end)
        results = QuizResult.objects.filter(quiz__lesson_id__in=lesson_ids).filter(quiz_filter) if lesson_ids else QuizResult.objects.none()
        avg_score = results.aggregate(value=Avg("score"))["value"]
        passed_lessons = sum(1 for lid in lesson_ids if QuizResult.objects.filter(quiz__lesson_id=lid, score__gte=60).exists())
        completion_pct = round((passed_lessons / len(lesson_ids)) * 100, 1) if lesson_ids else 0
        common_weak = (
            WeakTopic.objects.filter(user__enrollments__course_id=course.id)
            .values("topic_tag")
            .annotate(count=Count("id"))
            .order_by("-count")[:3]
        )
        weak_summary = ", ".join(row["topic_tag"] for row in common_weak) or "—"
        rows.append(
            [
                course.title,
                course.level,
                str(course.lesson_count or 0),
                str(enrolled),
                _fmt(round(float(avg_score), 1) if avg_score is not None else None),
                f"{completion_pct}%",
                weak_summary,
            ]
        )

    sections = [("Executive Summary", [("Courses included", len(rows))])]
    tables = [
        {
            "title": "Course Details",
            "headers": ["Course", "Level", "Lessons", "Enrolled", "Avg Score", "Completion", "Common Weak Topics"],
            "rows": rows,
        }
    ]
    report_title = courses[0].title if course_id else "All Courses"
    return _pdf_response(
        report_type="Course Performance Report",
        report_title=report_title,
        generated_by=admin_user.email,
        sections=sections,
        tables=tables,
    )


def build_admin_students_report(admin_user, *, student_id: int | None = None, from_date: str | None = None, to_date: str | None = None) -> bytes:
    start = _parse_date(from_date)
    end = _parse_date(to_date)
    course_ids = _admin_course_ids(admin_user)

    students = User.objects.filter(role=User.Role.STUDENT)
    if student_id:
        students = students.filter(pk=student_id)
        if not students.exists():
            raise ReportDataError("Invalid student id.", status_code=404)

    students = list(students.order_by("email")[:50])
    if not students:
        raise ReportDataError("No student data available.", status_code=404)

    if student_id:
        student = students[0]
        return _build_single_student_admin_report(
            student, course_ids, start, end, generated_by=admin_user.email
        )

    rows = []
    quiz_filter = _date_range_filter(start, end)
    for student in students:
        enrolled = Enrollment.objects.filter(user=student, course_id__in=course_ids).count()
        completed = LessonProgress.objects.filter(user=student, completed_at__isnull=False).count()
        results = QuizResult.objects.filter(user=student).filter(quiz_filter)
        attempts = results.count()
        avg_score = results.aggregate(value=Avg("score"))["value"]
        passed = results.filter(score__gte=60).values("quiz_id").distinct().count()
        failed = max(0, attempts - passed)
        weak_count = WeakTopic.objects.filter(user=student).count()
        rows.append(
            [
                student.email,
                student.experience_level or "—",
                str(enrolled),
                str(completed),
                str(attempts),
                _fmt(round(float(avg_score), 1) if avg_score is not None else None),
                str(passed),
                str(failed),
                str(weak_count),
            ]
        )

    sections = [("Executive Summary", [("Students included", len(rows))])]
    tables = [
        {
            "title": "Student Metrics",
            "headers": ["Email", "Level", "Enrolled", "Completed", "Attempts", "Avg Score", "Passed", "Failed", "Weak Topics"],
            "rows": rows,
        }
    ]
    return _pdf_response(
        report_type="Student Performance Report",
        report_title="All Students Overview",
        generated_by=admin_user.email,
        sections=sections,
        tables=tables,
    )


def _build_single_student_admin_report(
    student,
    course_ids: list[int],
    start: date | None,
    end: date | None,
    *,
    generated_by: str,
) -> bytes:
    from ai_engine.services.learning_path import generate_learning_path

    quiz_filter = _date_range_filter(start, end)
    enrolled_courses = list(
        Course.objects.filter(id__in=course_ids, enrollments__user=student)
        .distinct()
        .values_list("title", flat=True)
    )
    completed = LessonProgress.objects.filter(user=student, completed_at__isnull=False).count()
    results = QuizResult.objects.filter(user=student).filter(quiz_filter).select_related("quiz__lesson")
    attempts = results.count()
    avg_score = results.aggregate(value=Avg("score"))["value"]
    passed = results.filter(score__gte=60).values("quiz_id").distinct().count()
    failed = max(0, attempts - passed)
    weak_topics = list(
        WeakTopic.objects.filter(user=student).order_by("-last_updated").values_list("topic_tag", flat=True)[:10]
    )
    recs = list(
        Recommendation.objects.filter(user=student, status="active")
        .select_related("lesson")
        .order_by("-created_at")[:8]
    )
    path = generate_learning_path(student.id)
    path_summary = f"{path['progress'].get('completed_steps', 0)}/{path['progress'].get('total_steps', 0)} steps completed"

    sections = [
        (
            "Executive Summary",
            [
                ("Name", f"{student.first_name} {student.last_name}".strip() or student.email),
                ("Email", student.email),
                ("Learning level", student.experience_level or "—"),
                ("Enrolled courses", ", ".join(enrolled_courses) or "—"),
                ("Completed lessons", completed),
                ("Quiz attempts", attempts),
                ("Average score", round(float(avg_score), 1) if avg_score is not None else "—"),
                ("Passed quizzes", passed),
                ("Failed quizzes", failed),
                ("Learning path progress", path_summary),
            ],
        ),
    ]
    tables = [
        {
            "title": "Weak Topics",
            "headers": ["Topic Tag"],
            "rows": [[tag] for tag in weak_topics],
        },
        {
            "title": "Recommended Lessons",
            "headers": ["Lesson", "Reason"],
            "rows": [[rec.lesson.title, rec.reason[:80]] for rec in recs],
        },
    ]
    return _pdf_response(
        report_type="Student Performance Report",
        report_title=student.email,
        generated_by=generated_by,
        sections=sections,
        tables=tables,
    )


def build_admin_weaknesses_report(admin_user, *, from_date: str | None = None, to_date: str | None = None) -> bytes:
    _parse_date(from_date)
    _parse_date(to_date)
    course_ids = _admin_course_ids(admin_user)
    if not course_ids:
        raise ReportDataError("No courses available for weakness report.", status_code=404)

    weak_rows = list(
        WeakTopic.objects.filter(user__enrollments__course_id__in=course_ids)
        .values("topic_tag", "weakness_level")
        .annotate(
            student_count=Count("user_id", distinct=True),
            total_attempts=Count("id"),
        )
        .order_by("-student_count")[:25]
    )
    if not weak_rows:
        raise ReportDataError("No weak topic data available.", status_code=404)

    rows = [
        [
            row["topic_tag"],
            row["weakness_level"] or "—",
            str(row["student_count"]),
            str(row["total_attempts"]),
        ]
        for row in weak_rows
    ]
    sections = [("Executive Summary", [("Topics tracked", len(rows))])]
    tables = [
        {
            "title": "Weak Topics Across Platform",
            "headers": ["Topic", "Level", "Students", "Records"],
            "rows": rows,
        }
    ]
    return _pdf_response(
        report_type="Weak Topic Summary Report",
        report_title="Platform Weakness Analytics",
        generated_by=admin_user.email,
        sections=sections,
        tables=tables,
    )


def build_admin_ai_generation_report(admin_user) -> bytes:
    course_ids = _admin_course_ids(admin_user)
    lesson_ids = _admin_lesson_ids(course_ids)
    if not lesson_ids:
        raise ReportDataError("No lessons available for AI generation report.", status_code=404)

    quiz_qs = Quiz.objects.filter(lesson_id__in=lesson_ids).select_related("lesson")
    success = quiz_qs.filter(generation_status=Quiz.GenerationStatus.DONE).count()
    failed = quiz_qs.filter(generation_status=Quiz.GenerationStatus.FAILED).count()
    pending = quiz_qs.exclude(
        generation_status__in=[Quiz.GenerationStatus.DONE, Quiz.GenerationStatus.FAILED]
    ).count()

    rows = []
    for quiz in quiz_qs.order_by("-created_at")[:30]:
        processing = LessonAIProcessing.objects.filter(lesson_id=quiz.lesson_id).first()
        published = Question.objects.filter(quiz=quiz, is_published=True).count()
        total_q = Question.objects.filter(quiz=quiz).count()
        rows.append(
            [
                quiz.lesson.title,
                quiz.generation_status,
                processing.status if processing else "—",
                str(published),
                str(total_q),
                (quiz.generation_error or "")[:60] or "—",
            ]
        )

    sections = [
        (
            "Executive Summary",
            [
                ("Successful", success),
                ("Failed", failed),
                ("Pending / processing", pending),
            ],
        )
    ]
    tables = [
        {
            "title": "Recent Lesson Quiz Generations",
            "headers": ["Lesson", "Quiz Status", "AI Status", "Published Q", "Total Q", "Error"],
            "rows": rows,
        }
    ]
    return _pdf_response(
        report_type="AI Quiz Generation Status Report",
        report_title="AI Pipeline Status",
        generated_by=admin_user.email,
        sections=sections,
        tables=tables,
    )


def build_student_progress_report(user) -> bytes:
    from ai_engine.services.learning_path import generate_learning_path

    if user.role != User.Role.STUDENT:
        raise ReportDataError("Student reports are available to students only.", status_code=403)

    enrolled_ids = list(Enrollment.objects.filter(user=user).values_list("course_id", flat=True))
    lesson_ids = list(Lesson.objects.filter(course_id__in=enrolled_ids).values_list("id", flat=True))
    if not enrolled_ids:
        raise ReportDataError("No enrollment data available for report.", status_code=404)

    completed = LessonProgress.objects.filter(user=user, completed_at__isnull=False).count()
    passed = sum(1 for lid in lesson_ids if quiz_passed_for_lesson(user.id, lid))
    results = QuizResult.objects.filter(user=user)
    attempts = results.count()
    avg_score = results.aggregate(value=Avg("score"))["value"]
    passed_quizzes = results.filter(score__gte=60).values("quiz_id").distinct().count()
    failed_quizzes = max(0, attempts - passed_quizzes)
    weak_count = WeakTopic.objects.filter(user=user).count()
    rec_count = Recommendation.objects.filter(user=user, status="active").count()
    path = generate_learning_path(user.id)

    course_titles = list(Course.objects.filter(id__in=enrolled_ids).values_list("title", flat=True))
    sections = [
        (
            "Executive Summary",
            [
                ("Student", f"{user.first_name} {user.last_name}".strip() or user.email),
                ("Email", user.email),
                ("Learning level", user.experience_level or "—"),
                ("Enrolled courses", ", ".join(course_titles)),
                ("Lessons in enrolled courses", len(lesson_ids)),
                ("Lessons passed (quiz)", passed),
                ("Lessons completed (official)", completed),
                ("Quiz attempts", attempts),
                ("Average score", round(float(avg_score), 1) if avg_score is not None else "—"),
                ("Passed quizzes", passed_quizzes),
                ("Failed quizzes", failed_quizzes),
                ("Weak topics tracked", weak_count),
                ("Active recommendations", rec_count),
                (
                    "Learning path",
                    f"{path['progress'].get('completed_steps', 0)}/{path['progress'].get('total_steps', 0)} steps",
                ),
            ],
        ),
    ]
    rec_rows = [
        [rec["lesson_title"], rec.get("reason", "")[:80]]
        for rec in path.get("recommended_lessons", [])[:8]
    ]
    tables = [
        {
            "title": "Recommended Lessons",
            "headers": ["Lesson", "Reason"],
            "rows": rec_rows,
        }
    ]
    return _pdf_response(
        report_type="Student Progress Report",
        report_title="My Learning Progress",
        generated_by=user.email,
        sections=sections,
        tables=tables,
    )


def build_student_quiz_performance_report(user, *, from_date: str | None = None, to_date: str | None = None) -> bytes:
    if user.role != User.Role.STUDENT:
        raise ReportDataError("Student reports are available to students only.", status_code=403)

    start = _parse_date(from_date)
    end = _parse_date(to_date)
    quiz_filter = _date_range_filter(start, end)
    results = (
        QuizResult.objects.filter(user=user)
        .filter(quiz_filter)
        .select_related("quiz__lesson__course")
        .order_by("-taken_at")[:40]
    )
    if not results:
        raise ReportDataError("No quiz performance data available.", status_code=404)

    avg_score = QuizResult.objects.filter(user=user).filter(quiz_filter).aggregate(value=Avg("score"))["value"]
    passed = results.filter(score__gte=60).count()
    sections = [
        (
            "Executive Summary",
            [
                ("Total attempts", results.count()),
                ("Average score", round(float(avg_score), 1) if avg_score is not None else "—"),
                ("Passing attempts (≥60)", passed),
            ],
        )
    ]
    rows = [
        [
            row.quiz.lesson.title,
            row.quiz.lesson.course.title,
            str(row.score),
            "Pass" if row.score >= row.quiz.passing_score else "Fail",
            row.taken_at.strftime("%Y-%m-%d %H:%M"),
        ]
        for row in results
    ]
    tables = [
        {
            "title": "Quiz Attempts",
            "headers": ["Lesson", "Course", "Score", "Result", "Taken At"],
            "rows": rows,
        }
    ]
    return _pdf_response(
        report_type="Student Quiz Performance Report",
        report_title="My Quiz Performance",
        generated_by=user.email,
        sections=sections,
        tables=tables,
    )


def build_student_weaknesses_report(user) -> bytes:
    if user.role != User.Role.STUDENT:
        raise ReportDataError("Student reports are available to students only.", status_code=403)

    topics = list(WeakTopic.objects.filter(user=user).order_by("-last_updated"))
    if not topics:
        raise ReportDataError("No weak topic data available.", status_code=404)

    rows = []
    for topic in topics:
        accuracy = round((topic.correct_count / topic.attempt_count) * 100, 1) if topic.attempt_count else 0
        rows.append(
            [
                topic.topic_tag,
                topic.weakness_level or "—",
                str(topic.attempt_count),
                str(topic.correct_count),
                f"{accuracy}%",
                topic.last_updated.strftime("%Y-%m-%d"),
            ]
        )
    sections = [("Executive Summary", [("Topics tracked", len(rows))])]
    tables = [
        {
            "title": "Weak Topics",
            "headers": ["Topic", "Level", "Attempts", "Correct", "Accuracy", "Last Updated"],
            "rows": rows,
        }
    ]
    return _pdf_response(
        report_type="Student Weak Topics Report",
        report_title="My Weak Topics",
        generated_by=user.email,
        sections=sections,
        tables=tables,
    )


def build_student_learning_path_report(user) -> bytes:
    from ai_engine.services.learning_path import generate_learning_path

    if user.role != User.Role.STUDENT:
        raise ReportDataError("Student reports are available to students only.", status_code=403)

    path = generate_learning_path(user.id)
    learning_path = path.get("learning_path") or []
    if not learning_path and not path.get("weak_topics"):
        raise ReportDataError("No learning path data available.", status_code=404)

    progress = path.get("progress") or {}
    sections = [
        (
            "Executive Summary",
            [
                ("Completed steps", progress.get("completed_steps", 0)),
                ("Total steps", progress.get("total_steps", 0)),
                ("Completion", f"{progress.get('percent_complete', 0)}%"),
            ],
        ),
    ]
    path_rows = [
        [
            str(step.get("step", "")),
            step.get("lesson_title", "—"),
            step.get("course_title", "—"),
            step.get("status", "—"),
            (step.get("reason") or "")[:60],
        ]
        for step in learning_path[:20]
    ]
    weak_rows = [
        [wt.get("topic_tag", "—"), wt.get("weakness_level", "—"), str(wt.get("accuracy_percent", "—"))]
        for wt in path.get("weak_topics", [])[:10]
    ]
    tables = [
        {
            "title": "Learning Path Steps",
            "headers": ["Step", "Lesson", "Course", "Status", "Reason"],
            "rows": path_rows,
        },
        {
            "title": "Weak Topics Driving Path",
            "headers": ["Topic", "Level", "Accuracy %"],
            "rows": weak_rows,
        },
    ]
    return _pdf_response(
        report_type="Student Learning Path Report",
        report_title="My Learning Path",
        generated_by=user.email,
        sections=sections,
        tables=tables,
    )
